# Generated by Django 5.2.7 on 2025-11-04 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadReserva', models.IntegerField()),
                ('fechaReserva', models.DateField()),
                ('horaReserva', models.TimeField()),
                ('estadoReserva', models.CharField(choices=[('reservaActiva', 'Reserva Activa'), ('reservaCancelada', 'Reserva Cancelada')], default='reservaActiva', max_length=250)),
                ('itinerario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservaitinerario', to='administracion.itinerario')),
                ('puntoDePartidaReserva', models.ManyToManyField(related_name='puntosDePartida', to='administracion.puntoturistico')),
                ('recorridoReserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservaTurista', to='administracion.recorrido')),
                ('turista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservaTurista', to='perfil.turista')),
            ],
        ),
    ]
