# Generated by Django 5.2.7 on 2025-10-18 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorridoReserva', models.TextField(max_length=250)),
                ('cantidadReserva', models.IntegerField()),
                ('fechaReserva', models.DateField()),
                ('horaReserva', models.TimeField()),
                ('puntoDePartidaReserva', models.TextField()),
                ('estadoReseva', models.TextField(max_length=250)),
                ('itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaitinerario', to='administracion.itinerario')),
                ('turista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaTurista', to='perfil.turista')),
            ],
        ),
    ]
