# Generated by Django 5.2.7 on 2025-11-03 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='estadoReseva',
            new_name='estadoReserva',
        ),
    ]
