# Generated by Django 5.2.7 on 2025-10-15 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itinerarios', '0001_initial'),
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacionesAdministrador', to='perfil.administrador')),
                ('itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacionesItinerario', to='itinerarios.itinerario')),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacionesOperario', to='perfil.operario')),
            ],
        ),
    ]
