# Generated by Django 5.2.7 on 2025-10-15 21:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.TextField(max_length=8, unique=True)),
                ('correo', models.TextField(max_length=100)),
                ('apellido', models.TextField(max_length=50)),
                ('nombre', models.TextField(max_length=20)),
                ('usuario', models.TextField(max_length=15)),
                ('contraseña', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='perfil.persona')),
                ('domicilio', models.TextField(max_length=50)),
                ('categoria', models.TextField(max_length=20)),
            ],
            bases=('perfil.persona',),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='perfil.persona')),
                ('nombreInstitucion', models.TextField(max_length=100)),
                ('cuit', models.TextField(max_length=11, unique=True)),
            ],
            bases=('perfil.persona',),
        ),
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='perfil.persona')),
                ('domicilio', models.TextField(max_length=50)),
                ('categoria', models.TextField(max_length=20)),
            ],
            bases=('perfil.persona',),
        ),
        migrations.CreateModel(
            name='Turista',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='perfil.persona')),
                ('nacionalidad', models.TextField()),
            ],
            bases=('perfil.persona',),
        ),
    ]
