# Generated by Django 5.2.7 on 2025-10-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil', '0001_initial'),
        ('puntoTuristico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRecorrido', models.TimeField(max_length=100)),
                ('horarios', models.TimeField()),
                ('inicio', models.TextField(max_length=250)),
                ('final', models.TextField(max_length=250)),
                ('administradores', models.ManyToManyField(related_name='recorridosAdministrador', to='perfil.administrador')),
                ('puntosTuristicos', models.ManyToManyField(related_name='recorridosPuntosTuristicos', to='puntoTuristico.puntoturistico')),
            ],
        ),
    ]
