# Generated by Django 5.2.7 on 2025-10-15 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recorridos', '0001_initial'),
        ('reportes', '0001_initial'),
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('recorrido', models.TextField()),
                ('dominioTransporte', models.TextField(unique=True)),
                ('recorridos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorridoItinerario', to='recorridos.recorrido')),
                ('reportes', models.ManyToManyField(related_name='reportesNotificaciones', to='reportes.reportes')),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trasporteItinerario', to='transporte.transporte')),
            ],
        ),
    ]
