# Generated by Django 5.2.7 on 2025-10-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominioMatriculaTransporte', models.TextField(max_length=250, unique=True)),
                ('capacidadTransporte', models.IntegerField()),
                ('estadoTransporte', models.TextField(max_length=250)),
                ('administradores', models.ManyToManyField(related_name='transportesAdministrador', to='perfil.administrador')),
            ],
        ),
    ]
