# Generated by Django 5.2.7 on 2025-10-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=20)),
                ('ubicacion', models.TextField(max_length=100)),
                ('informacion', models.TextField(max_length=500)),
                ('imagen', models.FileField(upload_to='')),
                ('administrador', models.ManyToManyField(related_name='puntosTuristicosAdministrador', to='perfil.administrador')),
            ],
        ),
    ]
