# Generated by Django 5.2.7 on 2025-11-04 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacionesAdministrador', to=settings.AUTH_USER_MODEL)),
                ('itinerario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacionesItinerario', to='administracion.itinerario')),
                ('operario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacionesOperario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PuntoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=100)),
                ('informacion', models.TextField(max_length=500)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='puntos/')),
                ('administrador', models.ManyToManyField(related_name='puntosTuristicosAdministrador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRecorrido', models.CharField(max_length=100)),
                ('horarios', models.TimeField()),
                ('administradores', models.ManyToManyField(related_name='recorridosAdministrador', to=settings.AUTH_USER_MODEL)),
                ('final', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorridos_que_finalizan_aqui', to='administracion.puntoturistico')),
                ('inicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorridos_que_inician_aqui', to='administracion.puntoturistico')),
                ('puntosTuristicos', models.ManyToManyField(related_name='recorridosPuntosTuristicos', to='administracion.puntoturistico')),
            ],
        ),
        migrations.AddField(
            model_name='itinerario',
            name='recorridos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorridoItinerario', to='administracion.recorrido'),
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoReportes', models.CharField(choices=[('recoActivos', 'Recorridos Activos'), ('paradasMasUtilizadas', 'Paradas Mas Utilizadas'), ('reservaPorRecorrido', 'Reservas Por Recorrido'), ('consultaDeReservas', 'Consulta De Reservas'), ('estadisticasPasajeros', 'Estadisticas Pasajeros')], default='recoActivos', max_length=40)),
                ('formatoReporte', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=20)),
                ('horaFecha', models.DateTimeField()),
                ('identidadSolicitante', models.CharField(max_length=250)),
                ('administradores', models.ManyToManyField(related_name='reporteAdministrador', to=settings.AUTH_USER_MODEL)),
                ('clientes', models.ManyToManyField(related_name='reporteCliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='itinerario',
            name='reportes',
            field=models.ManyToManyField(related_name='reportesNotificaciones', to='administracion.reportes'),
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominioMatriculaTransporte', models.CharField(max_length=250, unique=True)),
                ('capacidadTransporte', models.IntegerField()),
                ('estadoTransporte', models.CharField(choices=[('activo', 'Activo'), ('averiado', 'Averiado'), ('reparacion', 'En Reparacion'), ('fueraServicio', 'Fuera de Servicio')], default='activo', max_length=20)),
                ('administradores', models.ManyToManyField(related_name='transportesAdministrador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='itinerario',
            name='transporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trasporteItinerario', to='administracion.transporte'),
        ),
    ]
