# Generated by Django 5.2.7 on 2025-10-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('recorrido', models.TextField()),
                ('dominioTransporte', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PuntoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=20)),
                ('ubicacion', models.TextField(max_length=100)),
                ('informacion', models.TextField(max_length=500)),
                ('imagen', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRecorrido', models.TimeField(max_length=100)),
                ('horarios', models.TimeField()),
                ('inicio', models.TextField(max_length=250)),
                ('final', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoReportes', models.TextField(max_length=250)),
                ('horaFecha', models.DateTimeField()),
                ('identidadSolicitante', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominioMatriculaTransporte', models.TextField(max_length=250, unique=True)),
                ('capacidadTransporte', models.IntegerField()),
                ('estadoTransporte', models.TextField(max_length=250)),
            ],
        ),
    ]
