# Generated by Django 5.2.7 on 2025-11-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PuntoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=100)),
                ('informacion', models.TextField(max_length=500)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='puntos/')),
            ],
        ),
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRecorrido', models.CharField(max_length=100)),
                ('horarios', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoReportes', models.CharField(choices=[('recoActivos', 'Recorridos Activos'), ('paradasMasUtilizadas', 'Paradas Mas Utilizadas'), ('reservaPorRecorrido', 'Reservas Por Recorrido'), ('consultaDeReservas', 'Consulta De Reservas'), ('estadisticasPasajeros', 'Estadisticas Pasajeros')], default='recoActivos', max_length=40)),
                ('formatoReporte', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=20)),
                ('horaFecha', models.DateTimeField()),
                ('identidadSolicitante', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominioMatriculaTransporte', models.CharField(max_length=250, unique=True)),
                ('capacidadTransporte', models.IntegerField()),
                ('estadoTransporte', models.CharField(choices=[('activo', 'Activo'), ('averiado', 'Averiado'), ('reparacion', 'En Reparacion'), ('fueraServicio', 'Fuera de Servicio')], default='activo', max_length=20)),
            ],
        ),
    ]
