# Generated by Django 5.2.7 on 2025-11-04 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='administrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacionesAdministrador', to='perfil.administrador'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='itinerario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacionesItinerario', to='administracion.itinerario'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='operario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacionesOperario', to='perfil.operario'),
        ),
        migrations.AddField(
            model_name='puntoturistico',
            name='administrador',
            field=models.ManyToManyField(related_name='puntosTuristicosAdministrador', to='perfil.administrador'),
        ),
        migrations.AddField(
            model_name='recorrido',
            name='administradores',
            field=models.ManyToManyField(related_name='recorridosAdministrador', to='perfil.administrador'),
        ),
        migrations.AddField(
            model_name='recorrido',
            name='final',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorridos_que_finalizan_aqui', to='administracion.puntoturistico'),
        ),
        migrations.AddField(
            model_name='recorrido',
            name='inicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorridos_que_inician_aqui', to='administracion.puntoturistico'),
        ),
        migrations.AddField(
            model_name='recorrido',
            name='puntosTuristicos',
            field=models.ManyToManyField(related_name='recorridosPuntosTuristicos', to='administracion.puntoturistico'),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='recorridos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorridoItinerario', to='administracion.recorrido'),
        ),
        migrations.AddField(
            model_name='reportes',
            name='administradores',
            field=models.ManyToManyField(related_name='reporteAdministrador', to='perfil.administrador'),
        ),
        migrations.AddField(
            model_name='reportes',
            name='clientes',
            field=models.ManyToManyField(related_name='reporteCliente', to='perfil.cliente'),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='reportes',
            field=models.ManyToManyField(related_name='reportesNotificaciones', to='administracion.reportes'),
        ),
        migrations.AddField(
            model_name='transporte',
            name='administradores',
            field=models.ManyToManyField(related_name='transportesAdministrador', to='perfil.administrador'),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='transporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trasporteItinerario', to='administracion.transporte'),
        ),
    ]
