# Generated by Django 5.2.7 on 2025-11-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerario',
            name='fecha',
            field=models.DateField(blank=True, null=True, unique=True, verbose_name='Fecha del Itinerario'),
        ),
    ]
