# Generated by Django 5.2.7 on 2025-11-05 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_itinerario_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerario',
            name='reportes',
        ),
        migrations.DeleteModel(
            name='Reportes',
        ),
    ]
