# Generated by Django 5.2.7 on 2025-11-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_itinerario_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntoturistico',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
    ]
