# Generated by Django 5.2.7 on 2025-11-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_alter_puntoturistico_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntoturistico',
            name='ubicacion',
            field=models.CharField(max_length=250),
        ),
    ]
