# Generated by Django 5.2.7 on 2025-10-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_remove_itinerario_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntoturistico',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='puntos/'),
        ),
    ]
