# Generated by Django 5.2.7 on 2025-10-25 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_puntoturistico_imagen'),
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='administrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacionesAdministrador', to='perfil.administrador'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='itinerario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacionesItinerario', to='administracion.itinerario'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='operario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacionesOperario', to='perfil.operario'),
        ),
    ]
