# Generated by Django 5.2.7 on 2025-11-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_puntoturistico_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerario',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Itinerario'),
        ),
    ]
