# Generated by Django 5.2.7 on 2025-11-05 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_remove_itinerario_reportes_delete_reportes'),
        ('administracion', '0005_alter_itinerario_fecha'),
    ]

    operations = [
    ]
