# Generated by Django 5.2.7 on 2025-11-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_merge_20251105_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='activo_en_home',
            field=models.BooleanField(default=False, verbose_name='Activa y visible en la página Home'),
        ),
    ]
