# Generated by Django 5.2.7 on 2025-11-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_notificacion_activo_en_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='activo_en_home',
            field=models.BooleanField(default=True, verbose_name='Activa y visible en la página Home'),
        ),
    ]
