# Generated by Django 5.2.7 on 2025-10-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoReportes', models.TextField(max_length=250)),
                ('horaFecha', models.DateTimeField()),
                ('identidadSolicitante', models.TextField()),
                ('administradores', models.ManyToManyField(related_name='reporteAdministrador', to='perfil.administrador')),
                ('clientes', models.ManyToManyField(related_name='reporteCliente', to='perfil.cliente')),
            ],
        ),
    ]
